wandb_version: 1

bootstrap:
  value: true
class_weight:
  value: balanced
max_depth:
  value: 20
min_samples_leaf:
  value: 2
min_samples_split:
  value: 10
n_estimators:
  value: 53
warm_start:
  value: true
