wandb_version: 1

bootstrap:
  value: false
class_weight:
  value: balanced_subsample
max_depth:
  value: 5
min_samples_leaf:
  value: 3
min_samples_split:
  value: 2
n_estimators:
  value: 32
warm_start:
  value: true
