wandb_version: 1

bootstrap:
  value: false
class_weight:
  value: balanced
max_depth:
  value: 6
min_samples_leaf:
  value: 1
min_samples_split:
  value: 3
n_estimators:
  value: 97
warm_start:
  value: true
