wandb_version: 1

bootstrap:
  value: true
class_weight:
  value: balanced
max_depth:
  value: 16
min_samples_leaf:
  value: 2
min_samples_split:
  value: 8
n_estimators:
  value: 56
warm_start:
  value: true
