wandb_version: 1

bootstrap:
  value: true
class_weight:
  value: balanced
max_depth:
  value: 2
min_samples_leaf:
  value: 3
min_samples_split:
  value: 9
n_estimators:
  value: 31
warm_start:
  value: false
