wandb_version: 1

bootstrap:
  value: true
class_weight:
  value: balanced_subsample
max_depth:
  value: 9
min_samples_leaf:
  value: 2
min_samples_split:
  value: 4
n_estimators:
  value: 93
warm_start:
  value: false
