wandb_version: 1

bootstrap:
  value: false
class_weight:
  value: balanced
max_depth:
  value: 18
min_samples_leaf:
  value: 4
min_samples_split:
  value: 10
n_estimators:
  value: 58
warm_start:
  value: true
