wandb_version: 1

bootstrap:
  value: true
class_weight:
  value: balanced
max_depth:
  value: 16
min_samples_leaf:
  value: 1
min_samples_split:
  value: 10
n_estimators:
  value: 63
warm_start:
  value: false
