wandb_version: 1

bootstrap:
  value: false
class_weight:
  value: balanced_subsample
max_depth:
  value: 16
min_samples_leaf:
  value: 4
min_samples_split:
  value: 4
n_estimators:
  value: 79
warm_start:
  value: true
