wandb_version: 1

bootstrap:
  value: false
class_weight:
  value: balanced
max_depth:
  value: 5
min_samples_leaf:
  value: 2
min_samples_split:
  value: 7
n_estimators:
  value: 94
warm_start:
  value: true
