wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/week2-b/homework-wandb/preprocess_data.py
    python_version: 3.10.10
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1685937047.294716
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.10
      5: 0.15.3
      8:
      - 2
      - 4
      - 5
