{
 "title": "homework",
 "time": { "from": "2023-02-28T15:00:00.000Z", "to": "2023-03-31T14:59:59.000Z" },
 "panels": [
  {
   "title": "prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "number of drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "fare amount q 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT fare_amount_quantile, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}