wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1685801591.561735
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.10.10
      5: 0.15.3
      8:
      - 1
      - 2
      - 4
      - 5
    session_history: code/_session_history.ipynb
